import { BarInfo, EventItem, MenuCategory, SignatureCocktail } from './types';

export const BAR_INFO: BarInfo = {
  name: "Beach Bar Corleone",
  locationName: "Plaža Cuklićevo, Malinska",
  address: "Cuklićevo bb",
  city: "51511 Malinska, Otok Krk",
  country: "Hrvatska / Croatia",
  phone: "+385 98 398 745",
  email: "corleone.malinska@gmail.com",
  instagram: "https://instagram.com/beachbarcorleone",
  facebook: "https://facebook.com/beachbarcorleone",
  mapsUrl: "https://maps.google.com/?q=Beach+Bar+Corleone+Malinska+Cuklicevo",
  coordinates: {
    lat: 45.1215,
    lng: 14.5262,
  },
  regularHours: "10:00 – 23:00",
  seasonNotice: {
    en: "Seasonal summer location. Open daily from May to October (weather permitting).",
    hr: "Sezonska lokacija. Otvoreno svakodnevno od svibnja do listopada (ovisno o vremenu).",
    de: "Saisonaler Sommerbetrieb. Täglich geöffnet von Mai bis Oktober (wetterabhängig).",
  },
};

export const SIGNATURE_COCKTAILS: SignatureCocktail[] = [
  {
    id: "corleone-sunset-spritz",
    name: "Corleone Sunset Spritz",
    category: "Signature Spritz",
    tagline: "The golden hour in a glass",
    description: {
      en: "Aperol, premium sparkling Prosecco DOC, fresh blood orange reduction, a splash of soda, and charred Adriatic rosemary.",
      hr: "Aperol, vrhunski Prosecco DOC, svježa redukcija crvene naranče, gazirana voda i grančica jadranskog ružmarina.",
      de: "Aperol, feiner Prosecco DOC, frische Blutorangen-Reduktion, Spritzer Soda und angeflämmter Rosmarin.",
    },
    ingredients: ["Aperol", "Prosecco DOC", "Blood Orange", "Sparkling Water", "Fresh Rosemary"],
    tasteProfile: {
      sweet: 3,
      sour: 2,
      bitter: 3,
      refreshing: 5,
    },
    alcoholContent: "11% Vol.",
    price: "€ 9.50",
    badge: "Most Loved Sunset Drink",
    color: "#E76F51",
  },
  {
    id: "adriatic-mist-gt",
    name: "Adriatic Mist Gin & Tonic",
    category: "Botanical Highball",
    tagline: "Distilled coastal herbs & crisp tonic",
    description: {
      en: "Artisanal Krk coastal gin infused with wild juniper, Mediterranean fever-tree tonic, cucumber ribbons, and crushed pink peppercorns.",
      hr: "Domaći jadranski gin s divljom klekom, mediteranski Fever-Tree tonik, svježi krastavac i ružičasti papar.",
      de: "Handwerklicher Küsten-Gin mit wildem Wacholder, mediterranes Fever-Tree Tonic, Gurkenschleife und rosa Pfeffer.",
    },
    ingredients: ["Local Krk Gin", "Mediterranean Tonic", "Juniper Berries", "Cucumber", "Pink Pepper"],
    tasteProfile: {
      sweet: 1,
      sour: 2,
      bitter: 4,
      refreshing: 5,
    },
    alcoholContent: "14% Vol.",
    price: "€ 10.00",
    badge: "Staff Favorite",
    color: "#2A9D8F",
  },
  {
    id: "cuklicevo-cliff-cooler",
    name: "Cuklićevo Cliff Cooler",
    category: "Tropical Refreshment",
    tagline: "Exotic passionfruit & mountain mint",
    description: {
      en: "Havana Club Añejo 3 Años, fresh passionfruit pulp, lime juice, brown cane sugar, mint leaves, topped with elderflower soda.",
      hr: "Havana Club rum, pulpa marakuje, svježi sok limete, smeđi šećer, listići mente i soda od bazge.",
      de: "Havana Club Rum, echtes Maracuja-Mark, Limettensaft, Rohrzucker, frische Minze und Holunderblüten-Soda.",
    },
    ingredients: ["Havana Club Rum", "Passionfruit", "Fresh Mint", "Lime", "Elderflower Soda"],
    tasteProfile: {
      sweet: 4,
      sour: 4,
      bitter: 1,
      refreshing: 5,
    },
    alcoholContent: "12% Vol.",
    price: "€ 9.50",
    badge: "Beach Pick",
    color: "#F4A261",
  },
  {
    id: "kvarner-lavender-sour",
    name: "Kvarner Lavender Sour",
    category: "Artisan Craft",
    tagline: "Silky texture with island botanical aroma",
    description: {
      en: "Makers Mark Bourbon, homemade organic Krk lavender syrup, freshly squeezed lemon juice, and silky aquafaba foam.",
      hr: "Bourbon viski, domaći sirup od krčke lavande, svježe cijeđeni limun i svilenkasta baršunasta pjena.",
      de: "Bourbon Whiskey, hausgemachter Krk-Lavendelsirup, frisch gepresster Zitronensaft und samtig-cremiger Schaum.",
    },
    ingredients: ["Bourbon Whiskey", "Island Lavender Syrup", "Fresh Lemon", "Angostura", "Silky Foam"],
    tasteProfile: {
      sweet: 3,
      sour: 4,
      bitter: 2,
      refreshing: 4,
    },
    alcoholContent: "15% Vol.",
    price: "€ 10.50",
    badge: "Craft Signature",
    color: "#9C8EB9",
  },
  {
    id: "espresso-martini-al-mare",
    name: "Espresso Martini Al Mare",
    category: "After Dark",
    tagline: "Fresh Illy espresso with a saline hint",
    description: {
      en: "Freshly pulled double Illy espresso, Absolut Vanilla vodka, Kahlúa coffee liqueur, and a delicate pinch of Nin sea salt.",
      hr: "Svježi dvostruki Illy espresso, Absolut Vanilla votka, Kahlúa liker i prstohvat ninske morske soli.",
      de: "Frischer doppelter Illy Espresso, Absolut Vanilla Vodka, Kahlúa Kaffeelikör und eine Prise Nin-Meersalz.",
    },
    ingredients: ["Fresh Espresso", "Vanilla Vodka", "Kahlúa", "Sugar Cane", "Fleur de Sel"],
    tasteProfile: {
      sweet: 3,
      sour: 1,
      bitter: 4,
      refreshing: 3,
    },
    alcoholContent: "16% Vol.",
    price: "€ 10.00",
    badge: "Night Starter",
    color: "#4A3E3D",
  },
  {
    id: "wild-fig-rosemary-fizz",
    name: "Wild Fig & Rosemary Fizz",
    category: "Mediterranean Low-ABV",
    tagline: "Sweet Adriatic figs & crisp sparkling wine",
    description: {
      en: "Artisanal Dalmatian fig liqueur, Tanqueray London Dry, fresh thyme, lemon twist, charged with dry Croatian Žlahtina sparkling wine.",
      hr: "Domaći liker od smokve, Tanqueray gin, svježi timijan, limun i pjenušac od autohtone krčke Žlahtine.",
      de: "Feiner Feigenlikör, Tanqueray Gin, frischer Thymian, Zitronentwist und prickelnder Krker Žlahtina-Schaumwein.",
    },
    ingredients: ["Wild Fig Liqueur", "Tanqueray Gin", "Fresh Thyme", "Lemon", "Žlahtina Sparkling"],
    tasteProfile: {
      sweet: 3,
      sour: 3,
      bitter: 1,
      refreshing: 5,
    },
    alcoholContent: "9% Vol.",
    price: "€ 9.00",
    badge: "Local Special",
    color: "#B56576",
  },
];

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "coffee",
    title: {
      en: "Coffee & Daytime Chill",
      hr: "Kava & Dnevno Osvježenje",
      de: "Kaffee & Tagestrinkkultur",
    },
    iconName: "Coffee",
    items: [
      {
        name: { en: "Espresso Illy", hr: "Espresso Illy", de: "Espresso Illy" },
        description: { en: "100% Arabica classic single shot", hr: "100% Arabica klasični espresso", de: "100% Arabica klassischer Single Shot" },
        price: "€ 2.20",
      },
      {
        name: { en: "Freddo Espresso / Cappuccino", hr: "Freddo Espresso / Cappuccino", de: "Freddo Espresso / Cappuccino" },
        description: { en: "Greek-style whipped cold espresso over ice", hr: "Hladni kremasti espresso s ledom", de: "Griechischer eisgekühlter Espresso mit Samtschaum" },
        price: "€ 3.80",
        isPopular: true,
      },
      {
        name: { en: "Iced Caramel Macchiato", hr: "Iced Caramel Macchiato", de: "Iced Caramel Macchiato" },
        description: { en: "Cold milk, espresso, homemade salted caramel", hr: "Hladno mlijeko, espresso, karamela", de: "Kalte Milch, Espresso, hausgemachtes Salzkaramell" },
        price: "€ 4.20",
      },
      {
        name: { en: "Espresso Tonic Al Limone", hr: "Espresso Tonic Al Limone", de: "Espresso Tonic Al Limone" },
        description: { en: "Chilled tonic water, fresh espresso float, lemon twist", hr: "Tonik, espresso na vrhu, limun", de: "Kaltes Tonic Water, Espresso-Schicht, Zitronenzeste" },
        price: "€ 4.50",
        isPopular: true,
      },
    ],
  },
  {
    id: "wine-beer",
    title: {
      en: "Wines & Local Beers",
      hr: "Vina & Domaća Piva",
      de: "Weine & Lokale Biere",
    },
    iconName: "Wine",
    items: [
      {
        name: { en: "Žlahtina Toljanić (Vrbnik, Krk)", hr: "Žlahtina Toljanić (Vrbnik)", de: "Žlahtina Toljanić (Vrbnik, Krk)" },
        description: { en: "Crisp, mineral, indigenous white wine 0.15l / 0.75l", hr: "Autohtono suho bijelo vino 0.15l / 0.75l", de: "Mineralisch-frischer, autochthoner Insel-Weißwein 0.15l / 0.75l" },
        price: "€ 4.50 / € 22.00",
        isPopular: true,
      },
      {
        name: { en: "Pošip Krajančić (Korčula)", hr: "Pošip Krajančić", de: "Pošip Krajančić (Korčula)" },
        description: { en: "Full-bodied Mediterranean dry white wine 0.15l", hr: "Bogato dalmatinsko bijelo vino 0.15l", de: "Körperreicher mediterraner Weißwein 0.15l" },
        price: "€ 5.50",
      },
      {
        name: { en: "San Servolo Craft Beer (Istria)", hr: "San Servolo Craft Pivo", de: "San Servolo Craft Beer (Istrien)" },
        description: { en: "Premium unpasteurized light / red craft beer 0.33l", hr: "Vrhunsko nepasterizirano svijetlo/crveno pivo", de: "Feinstes unpasteurisiertes Craft-Bier 0.33l" },
        price: "€ 4.80",
        isPopular: true,
      },
      {
        name: { en: "Ožujsko Draught Beer", hr: "Ožujsko Točeno Pivo", de: "Ožujsko Fassbier" },
        description: { en: "Crisp Croatian classic draught 0.33l / 0.5l", hr: "Svježe točeno pivo 0.33l / 0.5l", de: "Kroatischer Klassiker frisch gezapft 0.33l / 0.5l" },
        price: "€ 3.50 / € 4.50",
      },
    ],
  },
  {
    id: "mocktails",
    title: {
      en: "Virgin Cocktails & Coolers",
      hr: "Bezalkoholni Kokteli",
      de: "Alkoholfreie Mocktails & Eistees",
    },
    iconName: "GlassWater",
    items: [
      {
        name: { en: "Wild Berry Virgin Mojito", hr: "Wild Berry Virgin Mojito", de: "Wild Berry Virgin Mojito" },
        description: { en: "Fresh berries, mint leaves, lime juice, organic ginger ale", hr: "Bobičasto voće, menta, limeta, ginger ale", de: "Frische Waldbeeren, Minze, Limettensaft, Ginger Ale" },
        price: "€ 6.50",
        isPopular: true,
      },
      {
        name: { en: "Homemade Peach & Rosemary Iced Tea", hr: "Domaći Hladni Čaj Breskva-Ružmarin", de: "Hausgemachter Pfirsich-Rosmarin Eistee" },
        description: { en: "Cold brewed organic black tea with peach puree & garden herbs", hr: "Hladno kuhani crni čaj, breskva i začinsko bilje", de: "Kalt gebrühter Schwarztee mit Pfirsichmark & Kräutern" },
        price: "€ 4.80",
      },
      {
        name: { en: "Freshly Squeezed Citrus Lemonade", hr: "Svježa Limunada s Narančom", de: "Frische Zitrus-Limonade" },
        description: { en: "Lemon, orange, still water, mint, agave", hr: "Limun, naranča, voda, menta, agava", de: "Zitrone, Orange, Minze, Bio-Agavensirup" },
        price: "€ 4.50",
      },
    ],
  },
  {
    id: "bites",
    title: {
      en: "Coastal Bites & Gelato",
      hr: "Zalogaji & Sladoled",
      de: "Küsten-Snacks & Eis",
    },
    iconName: "Utensils",
    items: [
      {
        name: { en: "Krk Prosciutto & Pag Cheese Platter", hr: "Krčki Pršut & Paški Sir", de: "Krker Pršut & Pag-Käse Platte" },
        description: { en: "Aged island prosciutto, gold Pag sheep cheese, olives, grissini", hr: "Domaći pršut, paški sir, masline, grisini", de: "Gereifter Insel-Schinken, Pag-Schafskäse, Oliven, Grissini" },
        price: "€ 14.00",
        isPopular: true,
      },
      {
        name: { en: "Truffle & Parmesan Crunch Fries", hr: "Krumpirići s Tartufima & Parmezanom", de: "Trüffel-Parmesan Pommes" },
        description: { en: "Crisp potato dippers, Istrian black truffle mayo, grated aged parmesan", hr: "Hrskavi krumpirići, istarska krema od tartufa, parmezan", de: "Knusprige Fries, istrische Trüffel-Mayo, gereifter Parmesan" },
        price: "€ 7.50",
        isPopular: true,
      },
      {
        name: { en: "Mediterranean Tomato & Basil Bruschetta", hr: "Brusketi s Rajčicom & Bosiljkom", de: "Mediterrane Tomaten-Basilikum Bruschetta" },
        description: { en: "Toasted sourdough, ripe local tomatoes, extra virgin olive oil, garlic", hr: "Prepečeni kruh, domaća rajčica, maslinovo ulje, bosiljak", de: "Geröstetes Sauerteigbrot, sonnengereifte Tomaten, Olivenöl" },
        price: "€ 6.80",
      },
      {
        name: { en: "Artisan Gelato Scoop (Pistachio / Salted Caramel / Lemon-Mint)", hr: "Artisan Kuglica Sladoleda", de: "Artisan Gelato Kugel (Pistazie / Salzkaramell / Zitrone-Minze)" },
        description: { en: "Authentic Mediterranean gelato by scoop", hr: "Kremasti domaći sladoled po kuglici", de: "Echtes handwerkliches Gelato pro Kugel" },
        price: "€ 2.50",
      },
    ],
  },
];

export const EVENTS_DATA: EventItem[] = [
  {
    id: "sunset-session-fri",
    title: "Golden Hour Sunset Session",
    date: "Every Friday & Saturday",
    time: "18:30 – 23:00",
    djOrAct: "DJ Dugina & Guests",
    genre: "Deep House • Organic Beats • Melodic Sunset",
    description: {
      en: "Watch the sun sink into the Adriatic horizon while chilled sunset grooves, cocktails, and glowing cliffside vibes set the tone.",
      hr: "Uživajte u zalasku sunca uz opuštene ljetne ritmove, koktele i čarobnu atmosferu iznad plaže Cuklićevo.",
      de: "Erlebe den Sonnenuntergang über der Adria bei melodiösen Deep-House-Beats, kühlen Drinks und magischer Klippen-Stimmung.",
    },
    isTonight: true,
  },
  {
    id: "aperitivo-ritual",
    title: "Daily Sunset Aperitivo Ritual",
    date: "Every Day in Summer",
    time: "17:30 – 19:30",
    djOrAct: "Corleone Resident Sounds",
    genre: "Aperitivo Chill • Bossa • Coastal Lounge",
    description: {
      en: "Complimentary Mediterranean bar bites with every signature spritz or wine order as the golden hour begins.",
      hr: "Besplatni mediteranski zalogaji uz svaki signature spritz ili čašu vina tijekom zlatnog sata.",
      de: "Kostenfreie mediterrane Bar-Bites zu jedem Signature Spritz oder Wein beim Start der Golden Hour.",
    },
    isTonight: false,
  },
  {
    id: "trash-party-special",
    title: "Summer Special Night: Trash & 90s Hits",
    date: "Monthly Summer Highlight",
    time: "20:30 – 00:00",
    djOrAct: "DJ Special Host",
    genre: "90s / 2000s Pop & Dance Anthems",
    description: {
      en: "The legendary, carefree summer party night. High energy, sing-along classics, and ice-cold drinks under the starry sky.",
      hr: "Legendarna ljetna večer uz najveće hitove, veselu atmosferu i nezaboravnu zabavu pod zvijezdama.",
      de: "Die legendäre Sommernacht mit den größten Hits der 90er/2000er, ausgelassener Stimmung und Party unter dem Sternenhimmel.",
    },
    isTonight: false,
  },
];

export const DICTIONARY = {
  en: {
    nav: {
      experience: "The Cliff",
      drinks: "Drinks",
      events: "Events",
      location: "Location",
      openStatus: "Open Today",
      directions: "Directions",
    },
    hero: {
      eyebrow: "Cuklićevo Cliff • Malinska • Krk",
      titleStart: "SEA VIEWS.",
      titleAccent: "COCKTAILS.",
      titleEnd: "SUNSET VIBES.",
      subtitle: "Perched on the cliffs above Cuklićevo beach in Malinska. Your front-row seat to the Adriatic sunset, artisan coffee, craft cocktails, and laid-back summer nights.",
      btnRoute: "Start Route in Google Maps",
      btnMenu: "Drinks & Food Menu",
      btnEvents: "Tonight's Evening Program",
      liveBadge: "Open Today 10:00 – 23:00",
      walkInNote: "Walk-ins always welcome • Free entry",
    },
    liveRadar: {
      badge: "LIVE RADAR",
      heading: "Today at Beach Bar Corleone",
      statusOpen: "OPEN NOW",
      hoursLabel: "Today's Hours",
      hoursValue: "10:00 – 23:00",
      weatherLabel: "Coast Weather",
      weatherValue: "28°C • Sunny & Calm Sea",
      sunsetLabel: "Golden Hour & Sunset",
      sunsetValue: "approx. 20:15 CEST",
      tonightLabel: "Tonight's Vibe",
      tonightValue: "Sunset Chilled Beats & Spritz",
    },
    story: {
      eyebrow: "The Cuklićevo Experience",
      title: "Where the white rock meets the deep blue sea.",
      paragraph1: "Tucked away right above the picturesque pebble beach of Cuklićevo in Malinska, Beach Bar Corleone is more than a bar — it is a daily coastal ritual.",
      paragraph2: "Start your morning with freshly brewed Illy espresso and the murmur of gentle morning waves. Take a cooling dip in the turquoise water, and return at dusk when the sky turns fiery amber and our shakers start ringing.",
      card1Title: "Cliffside Panorama",
      card1Desc: "Unobstructed views over Kvarner Bay and the Adriatic horizon.",
      card2Title: "Artisan Cocktails",
      card2Desc: "Crafted with local botanicals, fresh juices, and premium spirits.",
      card3Title: "Easy Beach Access",
      card3Desc: "Just steps above Cuklićevo beach promenade. Dogs welcome.",
    },
    menu: {
      eyebrow: "Crafted for the Senses",
      title: "Drinks, Cocktails & Coastal Bites",
      subtitle: "From morning iced espressos to hand-crafted sunset signatures and refreshing wines from the island of Krk.",
      signaturesTitle: "Signature Cocktail Creations",
      flavorProfile: "Flavor Profile",
      sweet: "Sweet",
      sour: "Sour",
      bitter: "Bitter",
      refreshing: "Refreshing",
      allCategories: "Browse Full Category Menu",
      popularBadge: "Guest Favorite",
    },
    events: {
      eyebrow: "Summer Rhythm",
      title: "Sunset Sessions & Live Vibe",
      subtitle: "Good music, friendly people, and sea breezes. Check our schedule or follow our Instagram for spontaneous weekend specials.",
      tonightBadge: "Tonight's Event",
      instaCallout: "For real-time weather updates & special DJ announcements:",
      followInsta: "Follow @beachbarcorleone",
    },
    location: {
      eyebrow: "Plan Your Visit",
      title: "Finding Beach Bar Corleone",
      subtitle: "Located right above Plaža Cuklićevo in Malinska. Accessible on foot via the coastal promenade or by car with nearby parking.",
      addressLabel: "Address",
      phoneLabel: "Phone",
      emailLabel: "Email",
      openHoursLabel: "Hours",
      openHoursText: "Daily 10:00 – 23:00 (May – Oct)",
      consentNotice: "Click to load interactive map (Privacy-friendly OpenStreetMap).",
      loadMapBtn: "Load Interactive Map",
      openInMapsBtn: "Open in Google Maps",
      callUsBtn: "Call Now (+385 98 398 745)",
    },
    footer: {
      tagline: "Your cliffside haven above Cuklićevo beach in Malinska, Krk.",
      quickLinks: "Quick Navigation",
      legal: "Legal & Privacy",
      impressum: "Impressum / Legal Notice",
      privacy: "Datenschutzerklärung (DSGVO)",
      rights: "All rights reserved.",
      deCompliance: "100% DSGVO-konform • Keine Drittanbieter-Tracker ohne Einwilligung",
    },
    mobileBar: {
      route: "Route",
      call: "Call",
      menu: "Menu",
      status: "Open",
    },
  },
  hr: {
    nav: {
      experience: "O nama",
      drinks: "Pića",
      events: "Događanja",
      location: "Lokacija",
      openStatus: "Otvoreno danas",
      directions: "Navigacija",
    },
    hero: {
      eyebrow: "Plaža Cuklićevo • Malinska • Otok Krk",
      titleStart: "POGLED NA MORE.",
      titleAccent: "KOKTELI.",
      titleEnd: "ZALAZAK SUNCA.",
      subtitle: "Smješten na litici iznad plaže Cuklićevo u Malinskoj. Vaše prvo mjesto za najljepši zalazak sunca, vrhunsku kavu, signature koktele i opuštene ljetne večeri.",
      btnRoute: "Pokreni rutu u Google Kartama",
      btnMenu: "Karta Pića i Hrane",
      btnEvents: "Večernji Program & DJ",
      liveBadge: "Otvoreno danas 10:00 – 23:00",
      walkInNote: "Svi su dobrodošli • Ulaz slobodan",
    },
    liveRadar: {
      badge: "LIVE RADAR",
      heading: "Danas u Beach Baru Corleone",
      statusOpen: "OTVORENO",
      hoursLabel: "Radno vrijeme danas",
      hoursValue: "10:00 – 23:00",
      weatherLabel: "Vrijeme na obali",
      weatherValue: "28°C • Sunčano i mirno more",
      sunsetLabel: "Zalazak sunca",
      sunsetValue: "cca. 20:15 CEST",
      tonightLabel: "Večerašnji program",
      tonightValue: "Sunset Chilled Beats & Spritz",
    },
    story: {
      eyebrow: "Doživljaj Cuklićevo",
      title: "Gdje se krčki kamen susreće s tirkiznim morem.",
      paragraph1: "Smješten neposredno iznad šljunčane plaže Cuklićevo u Malinskoj, Beach Bar Corleone više je od bara — to je svakodnevni obalni ritual.",
      paragraph2: "Započnite jutro uz svježe pripremljeni Illy espresso i šum valova. Osvježite se u kristalnom moru i vratite se u suton kada nebo poprimi vatrene tonove.",
      card1Title: "Panoramski pogled",
      card1Desc: "Nesmetan pogled na Kvarnerski zaljev i jadranski horizont.",
      card2Title: "Vrhunski kokteli",
      card2Desc: "Pripremljeni s lokalnim biljem, svježim voćem i premium pićima.",
      card3Title: "Lagan pristup plaži",
      card3Desc: "Nekoliko koraka od šetnice plaže Cuklićevo. Kućni ljubimci dobrodošli.",
    },
    menu: {
      eyebrow: "Stvoreno za uživanje",
      title: "Pića, Kokteli & Zalogaji",
      subtitle: "Od jutarnjeg hladnog espressa do ručno rađenih signature koktela i vrhunskih krčkih vina.",
      signaturesTitle: "Signature Kokteli",
      flavorProfile: "Profil okusa",
      sweet: "Slatko",
      sour: "Kiselo",
      bitter: "Gorko",
      refreshing: "Osvježavajuće",
      allCategories: "Pregledaj cjelokupnu ponudu",
      popularBadge: "Preporuka gostiju",
    },
    events: {
      eyebrow: "Ljetni Ritam",
      title: "Sunset Sessions & Glazba",
      subtitle: "Odlična glazba, opušteni ljudi i morski povjetarac. Pratite naš Instagram za najnovije najave.",
      tonightBadge: "Događaj večeri",
      instaCallout: "Za najnovije vremenske obavijesti i DJ raspored:",
      followInsta: "Pratite @beachbarcorleone",
    },
    location: {
      eyebrow: "Posjetite nas",
      title: "Kako pronaći Beach Bar Corleone",
      subtitle: "Nalazimo se iznad plaže Cuklićevo u Malinskoj. Dostupno pješice obalnom šetnicom ili automobilom uz obližnji parking.",
      addressLabel: "Adresa",
      phoneLabel: "Telefon",
      emailLabel: "E-pošta",
      openHoursLabel: "Radno vrijeme",
      openHoursText: "Svakodnevno 10:00 – 23:00 (svibanj – listopad)",
      consentNotice: "Kliknite za učitavanje interaktivne karte (OpenStreetMap prilagođen privatnosti).",
      loadMapBtn: "Učitaj interaktivnu kartu",
      openInMapsBtn: "Otvori u Google Kartama",
      callUsBtn: "Nazovi odmah (+385 98 398 745)",
    },
    footer: {
      tagline: "Vaša oaza na litici iznad plaže Cuklićevo u Malinskoj na otoku Krku.",
      quickLinks: "Brza navigacija",
      legal: "Pravne informacije",
      impressum: "Impresum",
      privacy: "Pravila privatnosti (GDPR)",
      rights: "Sva prava pridržana.",
      deCompliance: "100% u skladu s GDPR-om • Bez praćenja bez pristanka",
    },
    mobileBar: {
      route: "Ruta",
      call: "Poziv",
      menu: "Meni",
      status: "Otvoreno",
    },
  },
  de: {
    nav: {
      experience: "Erlebnis",
      drinks: "Drinks",
      events: "Events",
      location: "Standort",
      openStatus: "Heute geöffnet",
      directions: "Route",
    },
    hero: {
      eyebrow: "Klippe Cuklićevo • Malinska • Insel Krk",
      titleStart: "MEERBLICK.",
      titleAccent: "COCKTAILS.",
      titleEnd: "SUNSET VIBES.",
      subtitle: "Erhaben auf den Felsen über dem Strand Cuklićevo in Malinska. Dein Logenplatz für den Sonnenuntergang über der Adria, erlesenen Espresso, Craft-Cocktails und entspannte Sommerabende.",
      btnRoute: "Route in Google Maps",
      btnMenu: "Speise- & Getränkekarte",
      btnEvents: "Abendprogramm & DJ-Lineup",
      liveBadge: "Heute geöffnet: 10:00 – 23:00 Uhr",
      walkInNote: "Walk-ins jederzeit willkommen • Eintritt frei",
    },
    liveRadar: {
      badge: "LIVE-RADAR",
      heading: "Heute in der Beach Bar Corleone",
      statusOpen: "JETZT GEÖFFNET",
      hoursLabel: "Heutige Öffnungszeit",
      hoursValue: "10:00 – 23:00 Uhr",
      weatherLabel: "Küstenwetter",
      weatherValue: "28°C • Sonnig & ruhige See",
      sunsetLabel: "Sonnenuntergang & Golden Hour",
      sunsetValue: "ca. 20:15 Uhr MESZ",
      tonightLabel: "Heutige Abendstimmung",
      tonightValue: "Sunset Chilled Beats & Spritz",
    },
    story: {
      eyebrow: "Das Cuklićevo-Erlebnis",
      title: "Wo weißer Kalkstein auf das tiefe Blau der Adria trifft.",
      paragraph1: "Direkt über dem malerischen Kiesstrand Cuklićevo in Malinska gelegen, ist die Beach Bar Corleone mehr als eine Bar – sie ist ein tägliches Küstenritual.",
      paragraph2: "Starte den Tag mit frisch gebrühtem Illy Espresso und dem sanften Meeresrauschen. Spring zur Abkühlung ins türkisblaue Wasser und kehre zur Dämmerung zurück, wenn der Himmel in feurigem Bernstein erglüht.",
      card1Title: "Klippen-Panorama",
      card1Desc: "Unverbauter Weitblick über die Kvarner Bucht und den Meereshorizont.",
      card2Title: "Artisan Cocktails",
      card2Desc: "Gemischt mit mediterranen Kräutern, frischen Säften & Premium-Spirituosen.",
      card3Title: "Direkter Strandzugang",
      card3Desc: "Nur wenige Schritte über der Strandpromenade Cuklićevo. Hunde willkommen.",
    },
    menu: {
      eyebrow: "Kreiert für alle Sinne",
      title: "Drinks, Cocktails & Küsten-Bites",
      subtitle: "Vom eisgekühlten Vormittags-Kaffee bis zu handgefertigten Sunset-Signaturen und feinen Insel-Weinen von Krk.",
      signaturesTitle: "Signature Cocktail Kreationen",
      flavorProfile: "Geschmacksprofil",
      sweet: "Süß",
      sour: "Sauer",
      bitter: "Herb",
      refreshing: "Erfrischend",
      allCategories: "Gesamte Barkarte durchstöbern",
      popularBadge: "Gäste-Favorit",
    },
    events: {
      eyebrow: "Sommer-Rhythmus",
      title: "Sunset Sessions & Live-Atmosphäre",
      subtitle: "Gute Musik, entspannte Menschen und Meeresbrise. Schau in unseren Plan oder folge unserem Instagram für spontane Wochenend-Specials.",
      tonightBadge: "Highlight des Abends",
      instaCallout: "Für tagesaktuelle Wetter-Updates & DJ-Ankündigungen:",
      followInsta: "@beachbarcorleone auf Instagram",
    },
    location: {
      eyebrow: "Dein Weg zu uns",
      title: "Beach Bar Corleone finden",
      subtitle: "Direkt über dem Strand Cuklićevo in Malinska. Zu Fuß über die Küstenpromenade oder per Auto mit nahegelegenen Parkmöglichkeiten erreichbar.",
      addressLabel: "Adresse",
      phoneLabel: "Telefon",
      emailLabel: "E-Mail",
      openHoursLabel: "Öffnungszeiten",
      openHoursText: "Täglich 10:00 – 23:00 Uhr (Mai – Okt)",
      consentNotice: "Klicken, um die interaktive Karte zu laden (Datenschutzfreundliches OpenStreetMap).",
      loadMapBtn: "Interaktive Karte laden",
      openInMapsBtn: "In Google Maps öffnen",
      callUsBtn: "Jetzt anrufen (+385 98 398 745)",
    },
    footer: {
      tagline: "Deine Klippen-Oase über dem Strand Cuklićevo in Malinska auf Krk.",
      quickLinks: "Navigation",
      legal: "Rechtliches & Datenschutz",
      impressum: "Impressum (§ 5 DDG)",
      privacy: "Datenschutzerklärung (DSGVO)",
      rights: "Alle Rechte vorbehalten.",
      deCompliance: "100% DSGVO-konform • Keine Drittanbieter-Tracker ohne Einwilligung",
    },
    mobileBar: {
      route: "Route",
      call: "Anruf",
      menu: "Karte",
      status: "Offen",
    },
  },
};
