import { BarInfo, EventItem, MenuCategory, SignatureCocktail } from './types';

export const BAR_INFO: BarInfo = {
  name: "Beach Bar Corleone",
  locationName: "Plaža Cuklićevo, Malinska",
  address: "Cuklićevo bb",
  city: "51511 Malinska, Otok Krk",
  country: "Hrvatska / Croatia",
  phone: "+385 98 398 745",
  email: "corleone.malinska@gmail.com",
  instagram: "https://instagram.com/beachbarcorleone",
  facebook: "https://facebook.com/beachbarcorleone",
  mapsUrl: "https://maps.google.com/?q=Beach+Bar+Corleone+Malinska+Cuklicevo",
  coordinates: {
    lat: 45.1215,
    lng: 14.5262,
  },
  regularHours: "10:00 – 23:00",
  seasonNotice: {
    en: "Seasonal summer location. Open daily from May to October (weather permitting).",
    hr: "Sezonska lokacija. Otvoreno svakodnevno od svibnja do listopada (ovisno o vremenu).",
    de: "Saisonaler Sommerbetrieb. Täglich geöffnet von Mai bis Oktober (wetterabhängig).",
  },
};

export const SIGNATURE_COCKTAILS: SignatureCocktail[] = [
  {
    id: "corleone-sunset-spritz",
    name: {
      en: "Corleone Sunset Spritz",
      hr: "Corleone Sunset Spritz",
      de: "Corleone Sunset Spritz",
    },
    category: {
      en: "Signature Spritz",
      hr: "Prepoznatljivi Spritz",
      de: "Signature Spritz",
    },
    tagline: {
      en: "The golden hour in a glass",
      hr: "Zlatni sat u čaši",
      de: "Die goldene Stunde im Glas",
    },
    description: {
      en: "Aperol, premium sparkling Prosecco DOC, fresh blood orange reduction, a splash of soda, and charred Adriatic rosemary.",
      hr: "Aperol, vrhunski Prosecco DOC, svježa redukcija crvene naranče, gazirana voda i grančica jadranskog ružmarina.",
      de: "Aperol, feiner Prosecco DOC, frische Blutorangen-Reduktion, Spritzer Soda und angeflämmter Rosmarin.",
    },
    ingredients: {
      en: ["Aperol", "Prosecco DOC", "Blood Orange", "Sparkling Water", "Fresh Rosemary"],
      hr: ["Aperol", "Prosecco DOC", "Crvena naranča", "Mineralna voda", "Svježi ružmarin"],
      de: ["Aperol", "Prosecco DOC", "Blutorange", "Soda", "Frischer Rosmarin"],
    },
    tasteProfile: {
      sweet: 3,
      sour: 2,
      bitter: 3,
      refreshing: 5,
    },
    alcoholContent: "11% Vol.",
    price: "€ 9.50",
    badge: {
      en: "Most Loved Sunset Drink",
      hr: "Omiljeni drink za zalazak",
      de: "Beliebtester Sunset-Drink",
    },
    color: "#E76F51",
  },
  {
    id: "adriatic-mist-gt",
    name: {
      en: "Adriatic Mist Gin & Tonic",
      hr: "Adriatic Mist Gin & Tonik",
      de: "Adriatic Mist Gin & Tonic",
    },
    category: {
      en: "Botanical Highball",
      hr: "Mediteranski Highball",
      de: "Botanical Highball",
    },
    tagline: {
      en: "Distilled coastal herbs & crisp tonic",
      hr: "Destilirano primorsko bilje i osvježavajući tonik",
      de: "Destillierte Küstenkräuter & frisches Tonic",
    },
    description: {
      en: "Artisanal Krk coastal gin infused with wild juniper, Mediterranean fever-tree tonic, cucumber ribbons, and crushed pink peppercorns.",
      hr: "Domaći jadranski gin s divljom klekom, mediteranski Fever-Tree tonik, svježi krastavac i ružičasti papar.",
      de: "Handwerklicher Küsten-Gin mit wildem Wacholder, mediterranes Fever-Tree Tonic, Gurkenschleife und rosa Pfeffer.",
    },
    ingredients: {
      en: ["Local Krk Gin", "Mediterranean Tonic", "Juniper Berries", "Cucumber", "Pink Pepper"],
      hr: ["Domaći krčki gin", "Mediteranski tonik", "Bobice kleka", "Krastavac", "Ružičasti papar"],
      de: ["Lokaler Krk-Gin", "Mediterranes Tonic", "Wacholderbeeren", "Gurke", "Rosa Pfeffer"],
    },
    tasteProfile: {
      sweet: 1,
      sour: 2,
      bitter: 4,
      refreshing: 5,
    },
    alcoholContent: "14% Vol.",
    price: "€ 10.00",
    badge: {
      en: "Staff Favorite",
      hr: "Preporuka osoblja",
      de: "Favorit des Hauses",
    },
    color: "#2A9D8F",
  },
  {
    id: "cuklicevo-cliff-cooler",
    name: {
      en: "Cuklićevo Cliff Cooler",
      hr: "Cuklićevo Obalni Cooler",
      de: "Cuklićevo Klippen-Cooler",
    },
    category: {
      en: "Tropical Refreshment",
      hr: "Tropsko osvježenje",
      de: "Tropische Erfrischung",
    },
    tagline: {
      en: "Exotic passionfruit & mountain mint",
      hr: "Egzotična marakuja i planinska menta",
      de: "Exotische Maracuja & Bergminze",
    },
    description: {
      en: "Havana Club Añejo 3 Años, fresh passionfruit pulp, lime juice, brown cane sugar, mint leaves, topped with elderflower soda.",
      hr: "Havana Club rum, pulpa marakuje, svježi sok limete, smeđi šećer, listići mente i soda od bazge.",
      de: "Havana Club Rum, echtes Maracuja-Mark, Limettensaft, Rohrzucker, frische Minze und Holunderblüten-Soda.",
    },
    ingredients: {
      en: ["Havana Club Rum", "Passionfruit", "Fresh Mint", "Lime", "Elderflower Soda"],
      hr: ["Havana Club rum", "Marakuja", "Svježa menta", "Limeta", "Soda od bazge"],
      de: ["Havana Club Rum", "Maracuja", "Frische Minze", "Limette", "Holunderblüten-Soda"],
    },
    tasteProfile: {
      sweet: 4,
      sour: 4,
      bitter: 1,
      refreshing: 5,
    },
    alcoholContent: "12% Vol.",
    price: "€ 9.50",
    badge: {
      en: "Beach Pick",
      hr: "Izbor plaže",
      de: "Beach-Favorit",
    },
    color: "#F4A261",
  },
  {
    id: "kvarner-lavender-sour",
    name: {
      en: "Kvarner Lavender Sour",
      hr: "Kvarnerski Sour od Lavande",
      de: "Kvarner Lavendel Sour",
    },
    category: {
      en: "Artisan Craft",
      hr: "Ručna izrada",
      de: "Artisan Craft",
    },
    tagline: {
      en: "Silky texture with island botanical aroma",
      hr: "Svilenkasta tekstura s aromom otočne lavande",
      de: "Seidige Textur mit Insel-Lavendelaroma",
    },
    description: {
      en: "Makers Mark Bourbon, homemade organic Krk lavender syrup, freshly squeezed lemon juice, and silky aquafaba foam.",
      hr: "Bourbon viski, domaći sirup od krčke lavande, svježe cijeđeni limun i baršunasta pjena.",
      de: "Bourbon Whiskey, hausgemachter Krk-Lavendelsirup, frisch gepresster Zitronensaft und samtig-cremiger Schaum.",
    },
    ingredients: {
      en: ["Bourbon Whiskey", "Island Lavender Syrup", "Fresh Lemon", "Angostura", "Silky Foam"],
      hr: ["Bourbon viski", "Sirup od krčke lavande", "Svježi limun", "Angostura", "Svilenkasta pjena"],
      de: ["Bourbon Whiskey", "Insel-Lavendelsirup", "Frische Zitrone", "Angostura", "Samtschaum"],
    },
    tasteProfile: {
      sweet: 3,
      sour: 4,
      bitter: 2,
      refreshing: 4,
    },
    alcoholContent: "15% Vol.",
    price: "€ 10.50",
    badge: {
      en: "Craft Signature",
      hr: "Autorski koktel",
      de: "Craft-Signature",
    },
    color: "#9C8EB9",
  },
  {
    id: "espresso-martini-al-mare",
    name: {
      en: "Espresso Martini Al Mare",
      hr: "Espresso Martini Al Mare",
      de: "Espresso Martini Al Mare",
    },
    category: {
      en: "After Dark",
      hr: "Večernji klasik",
      de: "After Dark",
    },
    tagline: {
      en: "Fresh Illy espresso with a saline hint",
      hr: "Svježi Illy espresso s daškom morske soli",
      de: "Frischer Illy Espresso mit feiner Meersalz-Note",
    },
    description: {
      en: "Freshly pulled double Illy espresso, Absolut Vanilla vodka, Kahlúa coffee liqueur, and a delicate pinch of Nin sea salt.",
      hr: "Svježi dvostruki Illy espresso, Absolut Vanilla votka, Kahlúa liker i prstohvat ninske morske soli.",
      de: "Frischer doppelter Illy Espresso, Absolut Vanilla Vodka, Kahlúa Kaffeelikör und eine Prise Nin-Meersalz.",
    },
    ingredients: {
      en: ["Fresh Espresso", "Vanilla Vodka", "Kahlúa", "Sugar Cane", "Fleur de Sel"],
      hr: ["Svježi espresso", "Votka od vanilije", "Kahlúa", "Smeđi šećer", "Ninski cvijet soli"],
      de: ["Frischer Espresso", "Vanille-Vodka", "Kahlúa", "Rohrzucker", "Fleur de Sel"],
    },
    tasteProfile: {
      sweet: 3,
      sour: 1,
      bitter: 4,
      refreshing: 3,
    },
    alcoholContent: "16% Vol.",
    price: "€ 10.00",
    badge: {
      en: "Night Starter",
      hr: "Početak noći",
      de: "Night Starter",
    },
    color: "#4A3E3D",
  },
  {
    id: "wild-fig-rosemary-fizz",
    name: {
      en: "Wild Fig & Rosemary Fizz",
      hr: "Fizz od Smokve i Ružmarina",
      de: "Wilde Feige & Rosmarin Fizz",
    },
    category: {
      en: "Mediterranean Low-ABV",
      hr: "Mediteranski lagani koktel",
      de: "Mediterraner Low-ABV",
    },
    tagline: {
      en: "Sweet Adriatic figs & crisp sparkling wine",
      hr: "Slatka jadranska smokva i krčki pjenušac",
      de: "Süße Adriatische Feigen & prickelnder Schaumwein",
    },
    description: {
      en: "Artisanal Dalmatian fig liqueur, Tanqueray London Dry, fresh thyme, lemon twist, charged with dry Croatian Žlahtina sparkling wine.",
      hr: "Domaći liker od smokve, Tanqueray gin, svježi timijan, limun i pjenušac od autohtone krčke Žlahtine.",
      de: "Feiner Feigenlikör, Tanqueray Gin, frischer Thymian, Zitronentwist und prickelnder Krker Žlahtina-Schaumwein.",
    },
    ingredients: {
      en: ["Wild Fig Liqueur", "Tanqueray Gin", "Fresh Thyme", "Lemon", "Žlahtina Sparkling"],
      hr: ["Liker od smokve", "Tanqueray gin", "Svježi timijan", "Limun", "Krčki pjenušac Žlahtina"],
      de: ["Feigenlikör", "Tanqueray Gin", "Frischer Thymian", "Zitrone", "Žlahtina-Schaumwein"],
    },
    tasteProfile: {
      sweet: 3,
      sour: 3,
      bitter: 1,
      refreshing: 5,
    },
    alcoholContent: "9% Vol.",
    price: "€ 9.00",
    badge: {
      en: "Local Special",
      hr: "Lokalni specijalitet",
      de: "Lokales Highlight",
    },
    color: "#B56576",
  },
];

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "coffee",
    title: {
      en: "Coffee & Daytime Chill",
      hr: "Kava & Dnevno Osvježenje",
      de: "Kaffee & Tagestrinkkultur",
    },
    iconName: "Coffee",
    items: [
      {
        name: { en: "Espresso Illy", hr: "Espresso Illy", de: "Espresso Illy" },
        description: { en: "100% Arabica classic single shot", hr: "100% Arabica klasični espresso", de: "100% Arabica klassischer Single Shot" },
        price: "€ 2.20",
      },
      {
        name: { en: "Freddo Espresso / Cappuccino", hr: "Freddo Espresso / Cappuccino", de: "Freddo Espresso / Cappuccino" },
        description: { en: "Greek-style whipped cold espresso over ice", hr: "Hladni kremasti espresso s ledom", de: "Griechischer eisgekühlter Espresso mit Samtschaum" },
        price: "€ 3.80",
        isPopular: true,
      },
      {
        name: { en: "Iced Caramel Macchiato", hr: "Iced Caramel Macchiato", de: "Iced Caramel Macchiato" },
        description: { en: "Cold milk, espresso, homemade salted caramel", hr: "Hladno mlijeko, espresso, karamela", de: "Kalte Milch, Espresso, hausgemachtes Salzkaramell" },
        price: "€ 4.20",
      },
      {
        name: { en: "Espresso Tonic Al Limone", hr: "Espresso Tonic Al Limone", de: "Espresso Tonic Al Limone" },
        description: { en: "Chilled tonic water, fresh espresso float, lemon twist", hr: "Tonik, espresso na vrhu, limun", de: "Kaltes Tonic Water, Espresso-Schicht, Zitronenzeste" },
        price: "€ 4.50",
        isPopular: true,
      },
    ],
  },
  {
    id: "wine-beer",
    title: {
      en: "Wines & Local Beers",
      hr: "Vina & Domaća Piva",
      de: "Weine & Lokale Biere",
    },
    iconName: "Wine",
    items: [
      {
        name: { en: "Žlahtina Toljanić (Vrbnik, Krk)", hr: "Žlahtina Toljanić (Vrbnik)", de: "Žlahtina Toljanić (Vrbnik, Krk)" },
        description: { en: "Crisp, mineral, indigenous white wine 0.15l / 0.75l", hr: "Autohtono suho bijelo vino 0.15l / 0.75l", de: "Mineralisch-frischer, autochthoner Insel-Weißwein 0.15l / 0.75l" },
        price: "€ 4.50 / € 22.00",
        isPopular: true,
      },
      {
        name: { en: "Pošip Krajančić (Korčula)", hr: "Pošip Krajančić", de: "Pošip Krajančić (Korčula)" },
        description: { en: "Full-bodied Mediterranean dry white wine 0.15l", hr: "Bogato dalmatinsko bijelo vino 0.15l", de: "Körperreicher mediterraner Weißwein 0.15l" },
        price: "€ 5.50",
      },
      {
        name: { en: "San Servolo Craft Beer (Istria)", hr: "San Servolo Craft Pivo", de: "San Servolo Craft Beer (Istrien)" },
        description: { en: "Premium unpasteurized light / red craft beer 0.33l", hr: "Vrhunsko nepasterizirano svijetlo/crveno pivo", de: "Feinstes unpasteurisiertes Craft-Bier 0.33l" },
        price: "€ 4.80",
        isPopular: true,
      },
      {
        name: { en: "Ožujsko Draught Beer", hr: "Ožujsko Točeno Pivo", de: "Ožujsko Fassbier" },
        description: { en: "Crisp Croatian classic draught 0.33l / 0.5l", hr: "Svježe točeno pivo 0.33l / 0.5l", de: "Kroatischer Klassiker frisch gezapft 0.33l / 0.5l" },
        price: "€ 3.50 / € 4.50",
      },
    ],
  },
  {
    id: "mocktails",
    title: {
      en: "Virgin Cocktails & Coolers",
      hr: "Bezalkoholni Kokteli",
      de: "Alkoholfreie Mocktails & Eistees",
    },
    iconName: "GlassWater",
    items: [
      {
        name: { en: "Wild Berry Virgin Mojito", hr: "Wild Berry Virgin Mojito", de: "Wild Berry Virgin Mojito" },
        description: { en: "Fresh berries, mint leaves, lime juice, organic ginger ale", hr: "Bobičasto voće, menta, limeta, ginger ale", de: "Frische Waldbeeren, Minze, Limettensaft, Ginger Ale" },
        price: "€ 6.50",
        isPopular: true,
      },
      {
        name: { en: "Homemade Peach & Rosemary Iced Tea", hr: "Domaći Hladni Čaj Breskva-Ružmarin", de: "Hausgemachter Pfirsich-Rosmarin Eistee" },
        description: { en: "Cold brewed organic black tea with peach puree & garden herbs", hr: "Hladno kuhani crni čaj, breskva i začinsko bilje", de: "Kalt gebrühter Schwarztee mit Pfirsichmark & Kräutern" },
        price: "€ 4.80",
      },
      {
        name: { en: "Freshly Squeezed Citrus Lemonade", hr: "Svježa Limunada s Narančom", de: "Frische Zitrus-Limonade" },
        description: { en: "Lemon, orange, still water, mint, agave", hr: "Limun, naranča, voda, menta, agava", de: "Zitrone, Orange, Minze, Bio-Agavensirup" },
        price: "€ 4.50",
      },
    ],
  },
  {
    id: "bites",
    title: {
      en: "Coastal Bites & Gelato",
      hr: "Zalogaji & Sladoled",
      de: "Küsten-Snacks & Eis",
    },
    iconName: "Utensils",
    items: [
      {
        name: { en: "Krk Prosciutto & Pag Cheese Platter", hr: "Krčki Pršut & Paški Sir", de: "Krker Pršut & Pag-Käse Platte" },
        description: { en: "Aged island prosciutto, gold Pag sheep cheese, olives, grissini", hr: "Domaći pršut, paški sir, masline, grisini", de: "Gereifter Insel-Schinken, Pag-Schafskäse, Oliven, Grissini" },
        price: "€ 14.00",
        isPopular: true,
      },
      {
        name: { en: "Truffle & Parmesan Crunch Fries", hr: "Krumpirići s Tartufima & Parmezanom", de: "Trüffel-Parmesan Pommes" },
        description: { en: "Crisp potato dippers, Istrian black truffle mayo, grated aged parmesan", hr: "Hrskavi krumpirići, istarska krema od tartufa, parmezan", de: "Knusprige Fries, istrische Trüffel-Mayo, gereifter Parmesan" },
        price: "€ 7.50",
        isPopular: true,
      },
      {
        name: { en: "Mediterranean Tomato & Basil Bruschetta", hr: "Brusketi s Rajčicom & Bosiljkom", de: "Mediterrane Tomaten-Basilikum Bruschetta" },
        description: { en: "Toasted sourdough, ripe local tomatoes, extra virgin olive oil, garlic", hr: "Prepečeni kruh, domaća rajčica, maslinovo ulje, bosiljak", de: "Geröstetes Sauerteigbrot, sonnengereifte Tomaten, Olivenöl" },
        price: "€ 6.80",
      },
      {
        name: { en: "Artisan Gelato Scoop (Pistachio / Salted Caramel / Lemon-Mint)", hr: "Artisan Kuglica Sladoleda", de: "Artisan Gelato Kugel (Pistazie / Salzkaramell / Zitrone-Minze)" },
        description: { en: "Authentic Mediterranean gelato by scoop", hr: "Kremasti domaći sladoled po kuglici", de: "Echtes handwerkliches Gelato pro Kugel" },
        price: "€ 2.50",
      },
    ],
  },
];

export const EVENTS_DATA: EventItem[] = [
  {
    id: "sunset-session-fri",
    title: {
      en: "Golden Hour Sunset Session",
      hr: "Sunset Session u Zlatni Sat",
      de: "Golden Hour Sunset Session",
    },
    date: {
      en: "Every Friday & Saturday",
      hr: "Svaki petak i subotu",
      de: "Jeden Freitag & Samstag",
    },
    time: "18:30 – 23:00",
    djOrAct: {
      en: "DJ Dugina & Guests",
      hr: "DJ Dugina & Gosti",
      de: "DJ Dugina & Guests",
    },
    genre: {
      en: "Deep House • Organic Beats • Melodic Sunset",
      hr: "Deep House • Opušteni ritmovi • Melodični zalazak",
      de: "Deep House • Organic Beats • Melodic Sunset",
    },
    description: {
      en: "Watch the sun sink into the Adriatic horizon while chilled sunset grooves, cocktails, and glowing cliffside vibes set the tone.",
      hr: "Uživajte u zalasku sunca uz opuštene ljetne ritmove, koktele i čarobnu atmosferu iznad plaže Cuklićevo.",
      de: "Erlebe den Sonnenuntergang über der Adria bei melodiösen Deep-House-Beats, kühlen Drinks und magischer Klippen-Stimmung.",
    },
    isTonight: true,
  },
  {
    id: "aperitivo-ritual",
    title: {
      en: "Daily Sunset Aperitivo Ritual",
      hr: "Svakodnevni Aperitivo Ritual",
      de: "Tägliches Sunset Aperitivo Ritual",
    },
    date: {
      en: "Every Day in Summer",
      hr: "Svaki dan u ljetnoj sezoni",
      de: "Täglich im Sommer",
    },
    time: "17:30 – 19:30",
    djOrAct: {
      en: "Corleone Resident Sounds",
      hr: "Corleone Resident Zvuk",
      de: "Corleone Resident Sounds",
    },
    genre: {
      en: "Aperitivo Chill • Bossa • Coastal Lounge",
      hr: "Aperitivo Chill • Bossa • Obalni Lounge",
      de: "Aperitivo Chill • Bossa • Coastal Lounge",
    },
    description: {
      en: "The Italian-inspired coastal ritual. Chilled spritz, golden sunsets, and complimentary Mediterranean bar snacks.",
      hr: "Tradicionalni talijanski obalni ritual. Hladni spritz, zlatni zalazak sunca i besplatni mediteranski zalogaji.",
      de: "Das mediterrane Ritual. Kühle Spritz-Variationen, goldener Sonnenuntergang und feine Aperitivo-Häppchen.",
    },
    isTonight: false,
  },
  {
    id: "trash-party-special",
    title: {
      en: "Summer Special Night: Trash & 90s Hits",
      hr: "Ljetni Party Specijal: Hitovi 90-ih i 2000-ih",
      de: "Sommer-Special: Trash & 90er Kult-Hits",
    },
    date: {
      en: "Monthly Summer Highlight",
      hr: "Mjesečni ljetni vrhunac",
      de: "Monatliches Sommer-Highlight",
    },
    time: "20:30 – 00:00",
    djOrAct: {
      en: "Special Guest DJ",
      hr: "Posebni gost DJ",
      de: "Special Guest DJ",
    },
    genre: {
      en: "90s / 2000s Pop & Dance Anthems",
      hr: "Pop i dance himne 90-ih i 2000-ih",
      de: "90er & 2000er Pop & Dance Klassiker",
    },
    description: {
      en: "The legendary, carefree summer party night. High energy, sing-along classics, and ice-cold drinks under the starry sky.",
      hr: "Legendarna ljetna večer uz najveće hitove, veselu atmosferu i nezaboravnu zabavu pod zvijezdama.",
      de: "Die legendäre Sommernacht mit den größten Hits der 90er/2000er, ausgelassener Stimmung und Party unter dem Sternenhimmel.",
    },
    isTonight: false,
  },
];

export const DICTIONARY = {
  en: {
    nav: {
      experience: "The Cliff",
      drinks: "Drinks & Menu",
      events: "Events & Music",
      location: "Location",
      openStatus: "Open Today",
      directions: "Directions",
    },
    hero: {
      eyebrow: "Cuklićevo Cliff • Malinska • Krk",
      titleStart: "SEA VIEWS.",
      titleAccent: "COCKTAILS.",
      titleEnd: "SUNSET VIBES.",
      subtitle: "Perched on the cliffs above Cuklićevo beach in Malinska. Your front-row seat to the Adriatic sunset, artisan coffee, craft cocktails, and laid-back summer nights.",
      btnRoute: "Start Route in Google Maps",
      btnMenu: "Drinks & Food Menu",
      btnEvents: "Tonight's Evening Program",
      scrollHint: "SCROLL TO EXPAND THE VIEW",
      liveBadge: "Open Today 10:00 – 23:00",
      walkInNote: "Walk-ins always welcome • Free entry",
    },
    story: {
      marquee: "THE CLIFFSIDE RITUAL • CUKLIĆEVO BEACH • ",
      eyebrow: "The Cuklićevo Experience",
      title: "Where the white rock meets the deep blue sea.",
      paragraph1: "Tucked away right above the picturesque pebble beach of Cuklićevo in Malinska, Beach Bar Corleone is more than a bar — it is a daily coastal ritual.",
      paragraph2: "Start your morning with freshly brewed Illy espresso and the murmur of gentle morning waves. Take a cooling dip in the turquoise water, and return at dusk when the sky turns fiery amber and our shakers start ringing.",
      stampTitle: "CLIFFSIDE PERCH",
      stampSubtitle: "100% Sea View",
      badgeMorning: "Morning Escape",
      badgeMorningSub: "Illy Espresso & Sea Dip",
      badgeSunset: "Golden Hour Spritz",
      stage1Time: "10:00 AM",
      stage1Title: "Morning Espresso & Swims",
      stage1Desc: "Quiet morning breeze, authentic Illy espresso, and steps down to the secluded pebble beach before the crowds arrive.",
      stage2Time: "17:30 PM",
      stage2Title: "The Golden Hour Spritz",
      stage2Desc: "The sky turns fiery amber, glasses clink with homemade rosemary spritz, and complimentary Mediterranean bar snacks are served.",
      stage3Time: "21:00 PM",
      stage3Title: "Starlit Beats & Gin",
      stage3Desc: "Lanterns illuminate the limestone tables, deep house rhythms echo across the water, and handcrafted gin tonics flow under the stars.",
    },
    dayNight: {
      title: "TWO WORLDS.",
      titleAccent: "ONE CLIFF.",
      subtitle: "Drag or hover across the curtain to reveal the morning serenity versus the nightfall rhythm at Cuklićevo.",
      dayBadge: "DAYTIME SERENITY",
      dayTitle: "Espresso & Morning Swims",
      dayDesc: "Silence of the cove, turquoise water, and freshly extracted coffee.",
      nightBadge: "NIGHTFALL CHILL",
      nightTitle: "DJ Grooves & Cocktails",
      nightDesc: "Lanterns glowing on limestone, music echoing across the sea.",
    },
    menu: {
      eyebrow: "Crafted for the Senses",
      title: "Drinks, Cocktails & Coastal Bites",
      subtitle: "From morning iced espressos to hand-crafted sunset signatures and refreshing wines from the island of Krk.",
      signaturesTitle: "Signature Cocktail Creations",
      craftedWith: "CRAFTED WITH:",
      abvLabel: "ALCOHOL BY VOLUME:",
      freshNotice: "Prepared fresh at the cliffside bar with crystal clear ice",
      vatNotice: "All prices in Euro (€) incl. VAT.",
      allCategories: "Browse Full Category Menu",
      popularBadge: "Guest Favorite",
    },
    events: {
      marquee: "SUNSET SESSIONS • LIVE DJS • NO DRESSCODE • ",
      eyebrow: "Summer Rhythm",
      title: "Sunset Sessions & Live Vibe",
      subtitle: "Good music, friendly people, and sea breezes. Check our schedule or follow our Instagram for spontaneous weekend specials.",
      tonightLineup: "TONIGHT'S LINE-UP",
      freeEntryNote: "Free Entry • No Guestlist Needed",
      checkStoryBtn: "Check Instagram Story",
      followSummer: "Follow the Summer",
    },
    location: {
      eyebrow: "Plan Your Visit",
      title: "Finding Beach Bar Corleone",
      subtitle: "Located right above Plaža Cuklićevo in Malinska. Accessible on foot via the coastal promenade or by car with nearby parking.",
      activeSpot: "ACTIVE SPOT",
      addressLabel: "Address",
      phoneLabel: "Phone & Direct Call",
      emailLabel: "Email",
      openHoursLabel: "Opening Hours",
      openHoursText: "Daily 10:00 – 23:00 (May – Oct)",
      cliffSubline: "Directly on the cliff above Plaža Cuklićevo",
      consentNotice: "Click to load interactive map (Privacy-friendly OpenStreetMap).",
      loadMapBtn: "Load Interactive Map",
      openInMapsBtn: "Open in Google Maps",
      dsgvoBadge: "2-Click Privacy Consent (Zero External Tracking)",
    },
    footer: {
      tagline: "Your cliffside haven above Cuklićevo beach in Malinska, Krk.",
      quickLinks: "Quick Navigation",
      contactHeading: "Contact & Location",
      legal: "Legal & Privacy",
      impressum: "Impressum / Legal Notice",
      privacy: "Privacy Policy (GDPR)",
      rights: "All rights reserved.",
      deCompliance: "100% GDPR-compliant • Zero external tracking without consent",
      impressumLink: "Impressum",
      privacyLink: "Privacy Policy",
    },
    mobileBar: {
      route: "Route",
      call: "Call",
      menu: "Menu",
      status: "Open",
    },
  },
  hr: {
    nav: {
      experience: "O nama",
      drinks: "Karta pića",
      events: "Događanja & DJ",
      location: "Lokacija",
      openStatus: "Otvoreno danas",
      directions: "Navigacija",
    },
    hero: {
      eyebrow: "Plaža Cuklićevo • Malinska • Otok Krk",
      titleStart: "POGLED\nNA MORE.",
      titleAccent: "KOKTELI.",
      titleEnd: "ZALAZAK\nSUNCA.",
      subtitle: "Smješten na litici iznad plaže Cuklićevo u Malinskoj. Vaše prvo mjesto za najljepši zalazak sunca, vrhunsku kavu, signature koktele i opuštene ljetne večeri.",
      btnRoute: "Pokreni rutu u Google Kartama",
      btnMenu: "Karta Pića i Hrane",
      btnEvents: "Večernji Program & DJ",
      scrollHint: "POMAKNITE ZA CIJELI POGLED",
      liveBadge: "Otvoreno danas 10:00 – 23:00",
      walkInNote: "Svi su dobrodošli • Ulaz slobodan",
    },
    story: {
      marquee: "RITUAL NA LITICI • PLAŽA CUKLIĆEVO • ",
      eyebrow: "Doživljaj Cuklićevo",
      title: "Gdje se krčki kamen susreće s tirkiznim morem.",
      paragraph1: "Smješten neposredno iznad šljunčane plaže Cuklićevo u Malinskoj, Beach Bar Corleone više je od bara — to je svakodnevni obalni ritual.",
      paragraph2: "Započnite jutro uz svježe pripremljeni Illy espresso i šum valova. Osvježite se u kristalnom moru i vratite se u suton kada nebo poprimi vatrene tonove.",
      stampTitle: "LITICA CUKLIĆEVO",
      stampSubtitle: "100% Pogled na more",
      badgeMorning: "Jutarnji bijeg",
      badgeMorningSub: "Illy espresso i kupanje",
      badgeSunset: "Spritz u zlatni sat",
      stage1Time: "10:00 h",
      stage1Title: "Jutarnji espresso & kupanje",
      stage1Desc: "Mirni jutarnji povjetarac, autentični Illy espresso i koraci do skrivene šljunčane plaže prije ljetne gužve.",
      stage2Time: "17:30 h",
      stage2Title: "Spritz u zlatni sat",
      stage2Desc: "Nebo poprima jantarnu boju, čaše zveckaju uz domaći spritz od ružmarina i poslužuju se besplatni mediteranski zalogaji.",
      stage3Time: "21:00 h",
      stage3Title: "Glazba pod zvijezdama & gin",
      stage3Desc: "Fenjeri osvjetljavaju kamene stolove, duboki house ritmovi odjekuju morem, a domaći gin-tonici teku pod zvjezdanim nebom.",
    },
    dayNight: {
      title: "DVA SVIJETA.",
      titleAccent: "JEDNA LITICA.",
      subtitle: "Povucite klizač za otkrivanje jutarnjeg mira u odnosu na noćni ritam na Cuklićevu.",
      dayBadge: "JUTARNJI MIR",
      dayTitle: "Espresso & Jutarnje kupanje",
      dayDesc: "Tišina uvale, tirkizno more i svježe pripremljena kava.",
      nightBadge: "NOĆNI RITAM",
      nightTitle: "DJ ritmovi & Kokteli",
      nightDesc: "Fenjeri na stijenama, glazba koja odjekuje morskom površinom.",
    },
    menu: {
      eyebrow: "Stvoreno za uživanje",
      title: "Pića, Kokteli & Zalogaji",
      subtitle: "Od jutarnjeg hladnog espressa do ručno rađenih signature koktela i vrhunskih krčkih vina.",
      signaturesTitle: "Signature Kokteli",
      craftedWith: "SASTOJCI:",
      abvLabel: "UDIO ALKOHOLA:",
      freshNotice: "Pripremljeno svježe na litici uz kristalno čist led",
      vatNotice: "Sve cijene su u eurima (€) uklj. PDV.",
      allCategories: "Pregledaj cjelokupnu ponudu",
      popularBadge: "Preporuka gostiju",
    },
    events: {
      marquee: "SUNSET SESSIONS • LIVE DJS • BEZ DRESS CODA • ",
      eyebrow: "Ljetni Ritam",
      title: "Sunset Sessions & Glazba",
      subtitle: "Odlična glazba, opušteni ljudi i morski povjetarac. Pratite naš raspored ili Instagram za najnovije najave.",
      tonightLineup: "VEČERAŠNJI PROGRAM",
      freeEntryNote: "Slobodan ulaz • Bez rezervacije",
      checkStoryBtn: "Pogledaj Instagram Story",
      followSummer: "Pratite naše ljeto",
    },
    location: {
      eyebrow: "Posjetite nas",
      title: "Kako pronaći Beach Bar Corleone",
      subtitle: "Nalazimo se iznad plaže Cuklićevo u Malinskoj. Dostupno pješice obalnom šetnicom ili automobilom uz obližnji parking.",
      activeSpot: "AKTIVNA LOKACIJA",
      addressLabel: "Adresa",
      phoneLabel: "Telefon i izravan poziv",
      emailLabel: "E-pošta",
      openHoursLabel: "Radno vrijeme",
      openHoursText: "Svakodnevno 10:00 – 23:00 (svibanj – listopad)",
      cliffSubline: "Direktno na litici iznad plaže Cuklićevo",
      consentNotice: "Kliknite za učitavanje interaktivne karte (OpenStreetMap prilagođen privatnosti).",
      loadMapBtn: "Učitaj interaktivnu kartu",
      openInMapsBtn: "Otvori u Google Kartama",
      dsgvoBadge: "2-Klika Privatnost (Bez vanjskog praćenja)",
    },
    footer: {
      tagline: "Vaša oaza na litici iznad plaže Cuklićevo u Malinskoj na otoku Krku.",
      quickLinks: "Brza navigacija",
      contactHeading: "Kontakt i lokacija",
      legal: "Pravne informacije",
      impressum: "Impresum",
      privacy: "Pravila privatnosti (GDPR)",
      rights: "Sva prava pridržana.",
      deCompliance: "100% u skladu s GDPR-om • Bez praćenja bez pristanka",
      impressumLink: "Impresum",
      privacyLink: "Privatnost",
    },
    mobileBar: {
      route: "Ruta",
      call: "Poziv",
      menu: "Meni",
      status: "Otvoreno",
    },
  },
  de: {
    nav: {
      experience: "Erlebnis",
      drinks: "Drinks & Karte",
      events: "Events & DJ",
      location: "Standort",
      openStatus: "Heute geöffnet",
      directions: "Route",
    },
    hero: {
      eyebrow: "Klippe Cuklićevo • Malinska • Insel Krk",
      titleStart: "MEERBLICK.",
      titleAccent: "COCKTAILS.",
      titleEnd: "SUNSET VIBES.",
      subtitle: "Erhaben auf den Felsen über dem Strand Cuklićevo in Malinska. Dein Logenplatz für den Sonnenuntergang über der Adria, erlesenen Espresso, Craft-Cocktails und entspannte Sommerabende.",
      btnRoute: "Route in Google Maps",
      btnMenu: "Speise- & Getränkekarte",
      btnEvents: "Abendprogramm & DJ-Lineup",
      scrollHint: "SCROLLEN FÜR VOLLEN AUSBLICK",
      liveBadge: "Heute geöffnet: 10:00 – 23:00 Uhr",
      walkInNote: "Walk-ins jederzeit willkommen • Eintritt frei",
    },
    story: {
      marquee: "DAS KLIPPEN-RITUAL • STRAND CUKLIĆEVO • ",
      eyebrow: "Das Cuklićevo-Erlebnis",
      title: "Wo weißer Kalkstein auf das tiefe Blau der Adria trifft.",
      paragraph1: "Direkt über dem malerischen Kiesstrand Cuklićevo in Malinska gelegen, ist die Beach Bar Corleone mehr als eine Bar – sie ist ein tägliches Küstenritual.",
      paragraph2: "Starte den Tag mit frisch gebrühtem Illy Espresso und dem sanften Meeresrauschen. Spring zur Abkühlung ins türkisblaue Wasser und kehre zur Dämmerung zurück, wenn der Himmel in feurigem Bernstein erglüht.",
      stampTitle: "KLIPPEN-LOGE",
      stampSubtitle: "100% Meerblick",
      badgeMorning: "Morgen-Flucht",
      badgeMorningSub: "Illy Espresso & Meerbad",
      badgeSunset: "Golden Hour Spritz",
      stage1Time: "10:00 Uhr",
      stage1Title: "Morgen-Espresso & Baden",
      stage1Desc: "Ruhige Morgenbrise, echter Illy Espresso und wenige Stufen zur einsamen Bucht, bevor die Strände erwachen.",
      stage2Time: "17:30 Uhr",
      stage2Title: "Der Golden Hour Spritz",
      stage2Desc: "Der Himmel erglüht in feurigem Bernstein, Gläser klingen mit hausgemachtem Rosmarin-Spritz und mediterrane Bites werden serviert.",
      stage3Time: "21:00 Uhr",
      stage3Title: "Sternenlicht-Beats & Gin",
      stage3Desc: "Laternen beleuchten die Kalksteintische, Deep-House-Beats hallen über das Wasser und feinste Gin Tonics fließen unterm Sternenhimmel.",
    },
    dayNight: {
      title: "ZWEI WELTEN.",
      titleAccent: "EINE KLIPPE.",
      subtitle: "Bewege den Schieberegler, um die morgendliche Gelassenheit und den nächtlichen Beat in Cuklićevo zu entdecken.",
      dayBadge: "TAGES-IDYLLE",
      dayTitle: "Espresso & Morgenschwimmen",
      dayDesc: "Stille der Bucht, türkisfarbenes Wasser und frisch gebrühter Espresso.",
      nightBadge: "NACHTLEBEN",
      nightTitle: "DJ-Grooves & Cocktails",
      nightDesc: "Laternenlicht auf Kalkstein, Musik über den Wellen.",
    },
    menu: {
      eyebrow: "Kreiert für alle Sinne",
      title: "Drinks, Cocktails & Küsten-Bites",
      subtitle: "Vom eisgekühlten Vormittags-Kaffee bis zu handgefertigten Sunset-Signaturen und feinen Insel-Weinen von Krk.",
      signaturesTitle: "Signature Cocktail Kreationen",
      craftedWith: "ZUTATEN:",
      abvLabel: "ALKOHOLGEHALT:",
      freshNotice: "Frisch zubereitet an der Klippenbar mit kristallklarem Eis",
      vatNotice: "Alle Preise in Euro (€) inkl. MwSt.",
      allCategories: "Gesamte Barkarte durchstöbern",
      popularBadge: "Gäste-Favorit",
    },
    events: {
      marquee: "SUNSET SESSIONS • LIVE DJS • KEIN DRESSCODE • ",
      eyebrow: "Sommer-Rhythmus",
      title: "Sunset Sessions & Live-Atmosphäre",
      subtitle: "Gute Musik, entspannte Menschen und Meeresbrise. Schau in unseren Plan oder folge unserem Instagram für spontane Wochenend-Specials.",
      tonightLineup: "HEUTIGES LINE-UP",
      freeEntryNote: "Freier Eintritt • Keine Gästeliste nötig",
      checkStoryBtn: "Instagram Story ansehen",
      followSummer: "Folge dem Sommer",
    },
    location: {
      eyebrow: "Dein Weg zu uns",
      title: "Beach Bar Corleone finden",
      subtitle: "Direkt über dem Strand Cuklićevo in Malinska. Zu Fuß über die Küstenpromenade oder per Auto mit nahegelegenen Parkmöglichkeiten erreichbar.",
      activeSpot: "AKTIVER SPOT",
      addressLabel: "Adresse",
      phoneLabel: "Telefon & Direktanruf",
      emailLabel: "E-Mail",
      openHoursLabel: "Öffnungszeiten",
      openHoursText: "Täglich 10:00 – 23:00 Uhr (Mai – Okt)",
      cliffSubline: "Direkt auf den Klippen über dem Strand Cuklićevo",
      consentNotice: "Klicken, um die interaktive Karte zu laden (Datenschutzfreundliches OpenStreetMap).",
      loadMapBtn: "Interaktive Karte laden",
      openInMapsBtn: "In Google Maps öffnen",
      dsgvoBadge: "2-Klick DSGVO-Einwilligung (Kein externes Tracking)",
    },
    footer: {
      tagline: "Deine Klippen-Oase über dem Strand Cuklićevo in Malinska auf Krk.",
      quickLinks: "Navigation",
      contactHeading: "Kontakt & Anfahrt",
      legal: "Rechtliches & Datenschutz",
      impressum: "Impressum (§ 5 DDG)",
      privacy: "Datenschutzerklärung (DSGVO)",
      rights: "Alle Rechte vorbehalten.",
      deCompliance: "100% DSGVO-konform • Keine Drittanbieter-Tracker ohne Einwilligung",
      impressumLink: "Impressum",
      privacyLink: "Datenschutz",
    },
    mobileBar: {
      route: "Route",
      call: "Anruf",
      menu: "Karte",
      status: "Offen",
    },
  },
};

